### ISSUE TITLE
Some random thoughts technical aspects of the project

### ISSUE THREAD

**Issue by Civil** [Percona-Lab/PromHouse#1]
1. GraphiteMergeTree if I'm correct will only work normally with exactly 4 column database: name, timestamp, value, date. I'm not sure that it'll be ok to use it with other set of columns. So I'd suggest to go for AggregatingMergeTree
2. You should allow people to create Replicated and Distributed tables. You also need to take into account that it's generally bad idea to insert directly to distributed table, but it's perfectly ok to read from it.
3. It doesn't really matter if you'll add an array of strings as a tag or you'll dynamically create columns that'll contain tags. In Clickhouse you can specify index only at table creation time, so all those columns will be out of index. In terms of query speed that won't be efficient. So it'll be much better if you'll have either another table that'll give you tags->names mapping.

You also should consider talking with developers in telegram chats about Clickhouse (https://t.me/clickhouse_ru or https://t.me/clickhouse_en)

**Comment by AlekSi** [comment]
Hi, sorry for the wait.

> GraphiteMergeTree if I'm correct will only work normally with exactly 4 column database

[Documentation](https://clickhouse.yandex/docs/ru/table_engines/graphitemergetree.html) says "at least the following columns". I also confirmed with developers that it should work. We want to use GraphiteMergeTree for downsampling of old data, that's essential for us.

> You also should consider talking with developers in telegram chats about Clickhouse 

In fact, I'm present in both chats, but I mostly talk with them at various conferences. :)

Thanks for the other points. At the moment PromHouse is "feature-complete" (meaning that both reads and writes work), and I also have some basic tests and benchmark, so now the fun parts start – both Go code optimizations and playing with database structure.

**Comment by Civil** [comment]
> I also confirmed with developers that it should work. We want to use GraphiteMergeTree for downsampling of old data, that's essential for us.

The question is how it will downsample the data? And again, AggregatingMergeTree might still be a better fit than GraphiteMergeTree.

**Comment by AlekSi** [comment]
Points 1 and 2 are covered by #8. Point 3 is no longer relevant – after testing/benchmarking schematic changed significantly.
